// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sda2.Cart.Persistance;

#nullable disable

namespace Sda2.Cart.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sda2.Cart.Persistance.Entites.Cart", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardId"));

                    b.Property<int>("CID")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("CardId");

                    b.HasIndex("CID");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Sda2.Cart.Persistance.Entites.CartInprogress", b =>
                {
                    b.Property<int>("CID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CID"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("CID");

                    b.ToTable("CartInprogress");
                });

            modelBuilder.Entity("Sda2.Cart.Persistance.Entites.ItemList", b =>
                {
                    b.Property<int>("ITID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ITID"));

                    b.Property<int>("CID")
                        .HasColumnType("int");

                    b.Property<int?>("CartInprogressCID")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("ITID");

                    b.HasIndex("CartInprogressCID");

                    b.ToTable("ItemLists");
                });

            modelBuilder.Entity("Sda2.Cart.Persistance.Entites.Cart", b =>
                {
                    b.HasOne("Sda2.Cart.Persistance.Entites.CartInprogress", "CartInprogress")
                        .WithMany("Carts")
                        .HasForeignKey("CID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CartInprogress");
                });

            modelBuilder.Entity("Sda2.Cart.Persistance.Entites.ItemList", b =>
                {
                    b.HasOne("Sda2.Cart.Persistance.Entites.CartInprogress", "CartInprogress")
                        .WithMany("ItemLists")
                        .HasForeignKey("CartInprogressCID");

                    b.Navigation("CartInprogress");
                });

            modelBuilder.Entity("Sda2.Cart.Persistance.Entites.CartInprogress", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("ItemLists");
                });
#pragma warning restore 612, 618
        }
    }
}
